### ISSUE TITLE
Slippage issue when resetting a market

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/morpho-blue#562]
Thought about this issue with @Rubilmax, in particular the idea for a general fix is his.

### Shares value in Morpho Blue

When a market becomes empty, the value of shares is resetted to the initial default rate of `VIRTUAL_ASSETS = 1` and `VIRTUAL_SHARES = 1e6`. This means that in effect an attacker can frontrun a transaction to change the value of shares. In Morpho Blue, shares value change like this:
1. value of both supply shares and borrow shares increase with accrued interest
2. value of supply shares goes up with roundings and value of borrow shares go down with roundings at each interaction. This effect is way smaller than the effect of 1
3. bad debt decreases the value of supply shares. This effect is potentially significant, and could be more than the effect of 1

Those effects have been verified with Certora [here](https://github.com/morpho-org/morpho-blue/blob/certora/dev/certora/specs/RatioMath.spec).

### Slippage issue for Morpho Blue

In practice those effects are not problematic for slippage because:
1. interests are accrued before each interaction anyway
2. this effect is negligible, we are talking about one WEI of difference
3. this effect is rare, and users are expected to lose when this happens. New suppliers should wait until bad debt is realized to ensure they incur no loss.

Resetting shares value does not have the same mitigation. Because of the above effects and their size, we can expect the value of shares to be greater than the initial value (we can discuss about this point below). So resetting decreases the shares value, which has different effects for supply and borrow:
- for the borrow side, users can take a smaller debt position than what they anticipated when they pass shares, but it does not come with the risk of entering a position too risky. Users can receive less assets than anticipated, which can make the rest of the transaction revert
- for the supply side, users can take a smaller supply position than what they anticipated when they pass shares, but it does not come with the risk of entering a position too risky because supply is not used as collateral. Users can leave more assets than anticipated on their funding account, which can potentially be lost if managed incorrectly (think of funds on the bundler contract that are then skimmed by someone else).

### General issue and potential solution

The more general issue comes with the solution that Morpho Blue has adopted to prevent shares manipulation. This solution is similar to the one of OZ in the vaults with the virtual assets and the virtual shares. This solution enforces a default ratio. Remark that enforcing a default ratio does not prevent sudden changes of ratio, which is at the core of this issue. Notice that, in the case of a vault, depositing a significant amount at creation prevents sudden changes of ratio. This is what motivates the following potential solution, by trying to reproduce a users taking significant positions right at the start:

In `createMarket`:
1. mint `VIRTUAL_SHARES` to `address(0)`
2. set `totalSupplyAssets = VIRTUAL_ASSETS` and `totalBorrowAssets = VIRTUAL_ASSETS`

Beware that the previous solution might be buggy and have unforeseen consequences

**Comment by MerlinEgalite** [comment]
It seems to me that the scenario in which it can happen is very rare:
- a market is empty or emptied
- someone wants to supply or borrow
- a malicious actor frontrun the tx to grief the user. Less assets assets are supplied or borrowed but it seems ok 

However, the proposed solutions seems simple but I have a hard time understanding the consequences:
- Should we send the asset at the market creation as well?
- Interest would be generated since now `totalBorrowAssets` would be greater than 0, what are the consequences?

**Comment by Rubilmax** [comment]
The suggested solution does not work and hasn't been investigated further, it's an embryo

**Comment by MathisGD** [comment]
Thanks for the detailed description. I think that we should acknoledge and add a comment on this somewhere.

**Comment by Rubilmax** [comment]
Additional comment on the topic that may be obvious: https://github.com/cantinasec/review-morpho-blue-1/issues/116#issuecomment-1807099548

**Comment by Rubilmax** [comment]
Actually,
> When a market becomes empty, the value of shares is resetted to the initial default rate of `VIRTUAL_ASSETS = 1` and `VIRTUAL_SHARES = 1e6`.

is incorrect: shares value is never reset, because virtual shares accrue interest

**Comment by Rubilmax** [comment]
Here's a summary of all observations we had when discussing about this issue with @QGarchery:

> [!IMPORTANT]
> Each point is worth to be well understood independently

1. Upon supply/withdraw, rounding directions lead to rounding up the exchange rate between supply shares & supply assets
2. Upon borrow/repay, rounding directions lead to rounding down the exchange rate between borrow shares & borrow assets
3. Upon bad debt realization:
- a) rounding directions lead to rounding down the exchange rate between supply shares & supply assets
- b) rounding directions lead to rounding up the exchange rate between borrow shares & borrow assets
4. Virtual supply assets accrue interest, which renders some assets in `totalSupplyAssets` to not be withdrawable, but to be **borrowable**
5. Virtual borrow assets accrue interest, which renders some assets in `totalBorrowAssets` to not be repayable

Conclusions:
1. From observation 1: there can be slippage to the **upside** in the expected amount of assets supplied (upside meaning: one supplies more assets than expected) when supplying an amount of supply shares
2. From observation 2: there can be slippage to the **downside** in the expected amount of assets  borrowed (downside meaning: one borrows fewer assets than expected) when borrowing an amount of borrow shares
3. From observation 2 + 3.b: there cannot be slippage to the **upside** in the expected amount of assets borrowed when borrowing an amount of borrow shares

Finally, let's quantify the slippage; because virtual assets are set to `1`, the slippage is capped to 50% in all directions, meaning:
- one may supply up to 100% more or 50% fewer assets than expected when supplying an amount of supply shares
  - exchange rate of 1.01 assets for 1e6 shares may get rounded up to 2 assets for 1e6 shares when the whole supply is withdrawn
  - exchange rate of 1.99 assets for 1e6 shares may get rounded down to 1 assets for 1e6 shares when the whole supply is bad debt and gets realized
- one may borrow up to 50% fewer assets than expected when borrowing an amount of borrow shares
  - exchange rate of 1.99 assets for 1e6 shares may get rounded down to 1 assets for 1e6 shares when the whole borrow is repaid

**Comment by QGarchery** [comment]
I think you can reword remark 3.a because it is not a rounding, it is just supply being removed and shares staying the same. But it has the same effect -> lowering the exchange rate.

Remark 3.b should be in the opposite direction too, it should be the same as repay. So reounding down the exchange rate.

Those affect the conclusion 3: you can have slippage to the downside in the expected amount of assets supplied
