### ISSUE TITLE
Morpho pinned to solc 0.8.19 make it incompatible with latest OpenZeppelin

### ISSUE THREAD

**Issue by codekoriko** [morpho-org/morpho-blue#672]
Any reason Morpho is pinned to solidity 0.8.19? is it a gas cost deterioration? 

Especially since you reverted back to 0.8.19 it in this [MR](https://github.com/morpho-org/morpho-blue/pull/378)

My issue is that, it makes it incompatible with the latest OpenZeppelin, which require 0.8.20

**Comment by MerlinEgalite** [comment]
Hey @codekoriko! What are you building? You can import the interface which is `>=0.5.0` if you want to interact with blue

**Comment by MathisGD** [comment]
>Any reason Morpho is pinned to solidity 0.8.19? 

the reason was to have the same bytecode on chains without support for `push0`, and be able to have the same address everywhere. An other option was to force the evm_version to paris, but we decided to go for 0.8.19 because it enforces the no push0 in the file directly.

> is it a gas cost deterioration?

as you can see in #378, it's only like ~60 gas on average.

>Especially since you reverted back to 0.8.19 it in this https://github.com/morpho-org/morpho-blue/pull/378
> 
> My issue is that, it makes it incompatible with the latest OpenZeppelin, which require 0.8.20

As Merlin said, in your source implementation you should only need the [IMorpho](https://github.com/morpho-org/morpho-blue/blob/main/src/interfaces/IMorpho.sol) interface, which has a looser solidity version.

And if you need Morpho Blue in your tests, you have two options:
- fork Ethereum and use the one deployed on chain (address [here](https://docs.morpho.org/contracts/morpho-blue/addresses)).
- use [deployCode](https://github.com/morpho-org/metamorpho/blob/98af1bf7224497cacbca972715690fecaffe25d6/test/forge/helpers/BaseTest.sol#L56), and force the compilation of Blue through a "import file" (see an example [here](https://github.com/morpho-org/metamorpho/blob/main/src/mocks/MorphoImport.sol)).

**Comment by codekoriko** [comment]
Coding an app that perform leverage of morpho Markets. Making the use callBacks as shown in your snippets: [LeverageDeleverageSnippets.sol](https://github.com/morpho-org/morpho-blue-snippets/blob/main/src/morpho-blue/LeverageDeleverageSnippets.sol)

So indeed I need Morpho Blue in my tests 

I'm Installing dependencies like so
`forge install morpho-org/morpho-blue morpho-org/morpho-blue-oracles`
That is `morpho-blue-oracles` that installs in turn OpenZeppelin to the latest version in it's `lib/`

The idea of the foundry's function [deployCode](https://book.getfoundry.sh/reference/forge-std/deployCode) is to import the bytecode of Morpho.sol, hence circumventing the incompatible solc issue?

**Comment by codekoriko** [comment]
> Otherwise, forking ethereum is even simpler: markets are already created and with liquidity, etc.

sounds like a good idea indeed 

> Interesting, what's the name of the project? 👀

I'm working on the Leveros Finance project 🚀
